PLATFORM 486 WIP
puente-dr/serverless pull request #5
Opened 2021-10-11 22:56 UTC by awalsh272

Adding functions for restCall and mainRecords into the appropriate repo, with some changes from the original made. Also added utility functions that are used in the data_loading script. Envisioning having separate py scripts for each survey form

2021-10-11 23:44 UTC, joseph-mccombs requested changes
A few little things. god work!

2021-10-11 23:44 UTC, joseph-mccombs commented on puente-data-exporter/lambdas/hello-world/restCall.py
> +def lambda_handler(event, context):
This handler should replace the handler in hello-world>index.py

2021-10-11 23:44 UTC, joseph-mccombs commented on puente-data-exporter/lambdas/hello-world/restCall.py
> +import json
For all of your imports that are not native to python like request, pandas etc. You should create a requirement.txt that contains the name of every library import. Can show you what i mean if unclear. File should be located in hello-world folder.

2021-10-11 23:44 UTC, joseph-mccombs commented on puente-data-exporter/lambdas/hello-world/utils.py
> +import re
these two should also be added to requirements.txt

2021-10-11 23:44 UTC, joseph-mccombs commented on puente-data-exporter/lambdas/hello-world/secretz.py
> +
remove from PR

2021-10-11 23:44 UTC, joseph-mccombs commented on puente-data-exporter/lambdas/hello-world/restCall.py
> +    specifier = "SurveyData"
should try to read the specficer from the event. The request coming in should look like this:

{
   surveyingOrganization: "Puente",
   parseClass: "SurveyData"
}

So you would want to insert those parameters in for specifier and where "OWS" is. Let me know if that needs clearing up.

2021-10-11 23:44 UTC, joseph-mccombs commented on puente-data-exporter/lambdas/hello-world/restCall.py
> +                "$in": ['OWS']
surveyingOrganization request param instead of OWS

2021-10-12 00:12 UTC, joseph-mccombs requested changes

2021-10-12 00:12 UTC, joseph-mccombs commented on puente-data-exporter/lambdas/hello-world/index.py
> +  if specifier == "SurveyData":
Right idea here. For some of the checks we're going to be doing, I want to make the rest call standard prior to doing all of the work for each form like cleaning. I essentially want:

restCall(specifier, survey_org)

* we will eventually do some checks here but not currently

Then break it out into the other form specfic work.

2021-10-12 00:12 UTC, joseph-mccombs commented on puente-data-exporter/lambdas/hello-world/index.py
> +    print("Pick a valid specifier")
We do have vitals and customForms too :)

2021-10-14 23:50 UTC, awalsh272 commented on puente-data-exporter/lambdas/hello-world/restCall.py
> +def lambda_handler(event, context):
index.py is the lambda, with fcn name "handler". Other scripts are called/referenced in index

2021-10-14 23:50 UTC, awalsh272 commented on puente-data-exporter/lambdas/hello-world/secretz.py
> +
I think I did this with a new commit?

2021-10-14 23:51 UTC, awalsh272 commented on puente-data-exporter/lambdas/hello-world/restCall.py
> +    specifier = "SurveyData"
Should be good now

2021-10-14 23:51 UTC, awalsh272 commented on puente-data-exporter/lambdas/hello-world/restCall.py
> +                "$in": ['OWS']
Should be good now

2021-10-14 23:56 UTC, awalsh272 commented on puente-data-exporter/lambdas/hello-world/utils.py
> +import re
added a requirements.txt

2021-12-13 23:10 UTC, closed without merging